---
- hosts: dev
  connection: local
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: copy file to destination
      copy:
        src: /tmp/Souad/index.html
        dst: /tmp/Souad/ansible-practice
